name: Test integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: verilator g++-13
          version: 1.0
      - name: Install verilator
        run: verilator --version
      - name: Install fusesoc
        run: |
          pip install fusesoc==2.3
          fusesoc --version
      - name: Run tests
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          git clone --depth=1 git@github.com:Purdue-SoCET/bus-components.git
          ssh-add -D - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          ssh-add - <<< '${{ secrets.DIGITAL_LIB_PRIVATE_KEY }}'
          git clone --depth=1 --branch=crc git@github.com:Purdue-SoCET/digital-lib.git
          make buildsys_setup
          ./apply_patches.sh digital-lib
          CXX=g++-13 fusesoc --cores-root . run --setup --build --build-root build --target sim --tool verilator socet:chiplet:endpoint
          CXX=g++-13 fusesoc --cores-root . run --setup --build --build-root build --target correctness --tool verilator socet:chiplet:switch
