name: Test integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: verilator
          version: 1.0
      - name: Install verilator
        run: verilator --version
      - name: Install fusesoc
        run: |
          pip install fusesoc==2.3
          fusesoc --version
      - name: Run tests
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          ssh-add - <<< '${{ secrets.DIGITAL_LIB_PRIVATE_KEY }}'
          git clone --depth=1 --branch=crc lib git@github.com:Purdue-SoCET/digital-lib.git
          git clone --depth=1 git@github.com:Purdue-SoCET/bus-components.git
          make buildsys_setup
          make versim_endpoint_src
