name: Test integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: verilator
          version: 1.0
      - name: Clone digital-lib
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'Purdue-SoCET'
          repository: 'digital-lib'
          access-token: ${{ secrets.DIGITAL_LIB_PRIVATE_KEY }}
      - name: Clone bus-components
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'Purdue-SoCET'
          repository: 'bus-components'
          access-token: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Install verilator
        run: verilator --version
      - name: Install fusesoc
        run: |
          pip install fusesoc==2.3
          fusesoc --version
      - name: Run tests
        run: |
          pushd digital-lib
          git checkout crc
          popd
          make buildsys_setup
          make versim_endpoint_src
